FROM node:22-alpine as builder
WORKDIR /app
COPY package*.json ./
COPY .env.prod .env
RUN npm ci
COPY . .

RUN npm run build -- --mode prod

FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf