name: Frontend Deploy Trigger

on: push

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createDispatchEvent({
              owner: 'chaparron',
              repo: 'timeTrackr',
              event_type: 'trigger-deploy'
            })